apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unyt-app-ingress
  namespace: unyt
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: unyt.pulami.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: unyt-app-service
                port:
                  number: 80
