apiVersion: v1
kind: Secret
metadata: 
  name: unyt-secrets
  namespace: unyt
type: Opaque
stringData:
  MONGODB_URI:
  REDIS_URL:
  CLERK_SECRET_KEY:
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY:
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME:
  CLOUDINARY_API_KEY:
  CLOUDINARY_API_SECRET:
  NEXT_PUBLIC_MAPBOX_TOKEN:
  NEXT_PUBLIC_BASE_URL:
